# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: David Moulton
email: dave@themoultons.net
description: > # this means to ignore newlines until "baseurl:"
  This is my personal website where I occaisionaly blog and
  post my astrophotography.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://davidmoulton.me" # the base hostname & protocol for your site
twitter_username: moultondj
github_username:  dmoulton
google_analytics: UA-20518309-1
astrobin_key: 2c284ca6393ceb538d753cb307b7dd8eb2b41144
astrobin_secret: c5637a20035f8ab070e38cc0171cd47dd164a76d

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: "astrophotography"
    values:
      permalink: /:path/:basename:output_ext

exclude: [LICENSE-CODE.md, LICENSE-IMAGES, README.md, bower.json]

# theme: jekyll-theme-slate
